// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://wmovopaqffanwophpouh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indtb3ZvcGFxZmZhbndvcGhwb3VoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3Njg1MzcsImV4cCI6MjA3MDM0NDUzN30.6EgVDmfWHW_Hcx2G_CQ_WzbL2lFeZ8dudO2mob2pltE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);